<?xml version="1.0"?>
<robot name="giraffe_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="ceiling_height" value="4.0" />
  <xacro:property name="arm_segment_length" value="0.5" />
  <xacro:property name="prismatic_max_extension" value="3.0" />  <!-- Reduced from 6.5m -->
  <xacro:property name="mic_arm_length" value="0.3" />

  <!-- Materials -->
  <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>
  <material name="green"><color rgba="0 1 0 1"/></material>  <!-- Fixed color -->
  <material name="blue"><color rgba="0 0 1 1"/></material>   <!-- Fixed color -->
  <material name="yellow"><color rgba="1 1 0 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="white"><color rgba="1 1 1 1"/></material>

  <link name="world"/>

  <!-- Base - Increased mass and corrected inertia -->
  <link name="base_link">
    <visual>
      <geometry><box size="0.2 0.2 0.05"/></geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry><box size="0.2 0.2 0.05"/></geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>  <!-- Increased from 2.0 -->
      <origin xyz="0 0 0"/>
      <!-- Corrected inertia for box: I = 1/12*m*(y²+z²) -->
      <inertia ixx="0.00417" ixy="0" ixz="0" iyy="0.00417" iyz="0" izz="0.00833"/>
    </inertial>
  </link>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="2.5 6.0 ${ceiling_height}" rpy="0 0 0"/>
  </joint>

  <!-- Link1: Pan - Corrected inertia for cylinder -->
  <link name="link1">
    <visual>
      <geometry><cylinder length="0.1" radius="0.05"/></geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry><cylinder length="0.1" radius="0.05"/></geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>  <!-- Increased from 0.3 -->
      <origin xyz="0 0 0"/>
      <!-- Ixx = Iyy = 1/12*m*(3*r² + h²), Izz = 1/2*m*r² -->
      <inertia ixx="0.00046" ixy="0" ixz="0" iyy="0.00046" iyz="0" izz="0.00125"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0.025" rpy="0 0 0"/>  <!-- Offset from base -->
    <axis xyz="0 0 1"/>
    <limit lower="-${M_PI}" upper="${M_PI}" effort="100" velocity="1"/>
    <dynamics damping="0.5"/>  <!-- Added damping -->
  </joint>

  <!-- Link2: Tilt - Corrected inertia and COM -->
  <link name="link2">
    <visual>
      <geometry><cylinder length="${arm_segment_length}" radius="0.03"/></geometry>
      <origin xyz="${arm_segment_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="${arm_segment_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <geometry><cylinder length="${arm_segment_length}" radius="0.03"/></geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>  <!-- Increased from 0.7 -->
      <origin xyz="${arm_segment_length/2} 0 0"/>  <!-- COM at center -->
      <!-- For cylinder along x: Ixx = 1/2*m*r², Iyy=Izz=1/12*m*(3r²+L²) -->
      <inertia ixx="0.0009" ixy="0" ixz="0" iyy="0.0417" iyz="0" izz="0.0417"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${2*M_PI/3}" upper="0" effort="100" velocity="1"/> <!-- Reduced range -->
    <dynamics damping="0.5"/>  <!-- Added damping -->
  </joint>

  <!-- Link3: Prismatic - Increased mass and corrected inertia -->
  <link name="link3">
    <visual>
      <geometry><box size="0.1 0.1 0.1"/></geometry>  <!-- More realistic than sphere -->
      <material name="blue"/>
    </visual>
    <collision>
      <geometry><box size="0.1 0.1 0.1"/></geometry>
    </collision>
    <inertial>
      <mass value="1.5"/>  <!-- Increased from 0.3 -->
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0025" ixy="0" ixz="0" iyy="0.0025" iyz="0" izz="0.0025"/>
    </inertial>
  </link>

  <joint name="joint3" type="prismatic">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${arm_segment_length} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="${prismatic_max_extension}" effort="10000" velocity="0.5"/>
    <dynamics damping="10.0" friction="2.0"/>  <!-- Increased damping -->
  </joint>

  <!-- Link4: Microphone bar - Corrected inertia -->
  <link name="link4">
    <visual>
      <geometry><cylinder length="${mic_arm_length}" radius="0.01"/></geometry>
      <origin xyz="${mic_arm_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <origin xyz="${mic_arm_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <geometry><cylinder length="${mic_arm_length}" radius="0.01"/></geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>  <!-- Increased from 0.1 -->
      <origin xyz="${mic_arm_length/2} 0 0"/>
      <!-- For cylinder along x: Ixx = 1/2*m*r², Iyy=Izz=1/12*m*(3r²+L²) -->
      <inertia ixx="0.000025" ixy="0" ixz="0" iyy="0.00377" iyz="0" izz="0.00377"/>
    </inertial>
  </link>

  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0.05 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="50" velocity="1"/>
    <dynamics damping="0.3"/>  <!-- Added damping -->
  </joint>

  <!-- End-effector: microphone - Corrected inertia -->
  <link name="ee_link">
    <visual>
      <geometry><box size="0.03 0.03 0.03"/></geometry>
      <material name="black"/>
    </visual>
    <visual>
      <geometry><cylinder length="0.2" radius="0.008"/></geometry>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <visual>
      <geometry><sphere radius="0.015"/></geometry>
      <origin xyz="0 0 -0.2" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry><sphere radius="0.03"/></geometry>  <!-- Simplified collision -->
    </collision>
    <inertial>
      <mass value="0.3"/>  <!-- Increased from 0.05 -->
      <origin xyz="0 0 -0.1"/>
      <!-- Approximate as point mass: I = m*d² -->
      <inertia ixx="0.003" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.003"/>
    </inertial>
  </link>

  <joint name="joint5" type="revolute">
    <parent link="link4"/>
    <child link="ee_link"/>
    <origin xyz="${mic_arm_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="50" velocity="1"/>
    <dynamics damping="0.2"/>  <!-- Added damping -->
  </joint>

</robot>