<?xml version="1.0"?>
<robot name="giraffe_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="ceiling_height" value="4.0" />
  <xacro:property name="arm_segment_length" value="0.5" />
  <xacro:property name="prismatic_max_extension" value="6.5" />
  <xacro:property name="mic_arm_length" value="0.3" />

  <!-- Materials -->
  <material name="gray"><color rgba="0 0 0 1"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>
  <material name="green"><color rgba="1 1 0 1"/></material>
  <material name="blue"><color rgba="1 0 0 1"/></material>
  <material name="yellow"><color rgba="1 1 0 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="white"><color rgba="1 1 1 1"/></material>

  <link name="world"/>

  <!-- Base -->
  <link name="base_link">
    <visual>
      <geometry><box size="0.2 0.2 0.05"/></geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry><box size="0.2 0.2 0.05"/></geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.003" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="2.5 6.0 ${ceiling_height}" rpy="0 0 0"/>
  </joint>

  <!-- Link1: Pan -->
  <link name="link1">
    <visual>
      <geometry><cylinder length="0.1" radius="0.05"/></geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry><cylinder length="0.1" radius="0.05"/></geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy="0 ${M_PI} 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${M_PI}" upper="${M_PI}" effort="100" velocity="1"/>
  </joint>

  <!-- Link2: Tilt -->
  <link name="link2">
    <visual>
      <geometry><cylinder length="${arm_segment_length}" radius="0.03"/></geometry>
      <origin xyz="${arm_segment_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="${arm_segment_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <geometry><cylinder length="${arm_segment_length}" radius="0.03"/></geometry>
    </collision>
    <inertial>
      <mass value="0.7"/>
      <origin xyz="${arm_segment_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${M_PI}" upper="0" effort="100" velocity="1"/>
  </joint>

  <!-- Link3: Prismatic -->
  <link name="link3">
    <visual>
      <geometry><sphere radius="0.05"/></geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry><sphere radius="0.05"/></geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="joint3" type="prismatic">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${arm_segment_length} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="${prismatic_max_extension}" effort="10000" velocity="0.5"/>
    <dynamics damping="5.0" friction="1.0"/>
  </joint>

  <!-- Link4: Microphone bar -->
  <link name="link4">
    <visual>
      <geometry><cylinder length="${mic_arm_length}" radius="0.01"/></geometry>
      <origin xyz="${mic_arm_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <origin xyz="${mic_arm_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <geometry><cylinder length="${mic_arm_length}" radius="0.01"/></geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="${mic_arm_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00002"/>
    </inertial>
  </link>

  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0.05 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="50" velocity="1"/>
  </joint>

  <!-- End-effector: microphone -->
  <link name="ee_link">
    <visual>
      <geometry><box size="0.03 0.03 0.03"/></geometry>
      <material name="black"/>
    </visual>
    <visual>
      <geometry><cylinder length="0.2" radius="0.008"/></geometry>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <visual>
      <geometry><sphere radius="0.015"/></geometry>
      <origin xyz="0 0 -0.2" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <geometry><cylinder length="0.2" radius="0.015"/></geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.000005"/>
    </inertial>
  </link>

  <joint name="joint5" type="revolute">
    <parent link="link4"/>
    <child link="ee_link"/>
    <origin xyz="${mic_arm_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="50" velocity="1"/>
  </joint>

</robot>
